FROM python:3.10-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    build-essential \
    libglib2.0-0 \
    libsm6 \
    libxext6 \
    libxrender-dev \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --upgrade pip && pip install -r requirements.txt

COPY additive_synthesis.py .

EXPOSE 8501

CMD ["streamlit", "run", "additive_synthesis.py", "--server.port=8501", "--server.address=0.0.0.0"]
