FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --upgrade pip && pip install -r requirements.txt

COPY additive_synthesis.py .

EXPOSE 7860

CMD ["python", "additive_synthesis.py"]
